package com.askeralim.user;

import java.util.Date;

/**
 * Dbuser generated by hbm2java
 */
public class User implements java.io.Serializable {
 
	private int userId;
	private String username;
 
	public User() {
	}
 
	public User(int userId, String username) {
		this.userId = userId;
		this.username = username;
	}
 
	public int getUserId() {
		return this.userId;
	}
 
	public void setUserId(int userId) {
		this.userId = userId;
	}
 
	public String getUsername() {
		return this.username;
	}
 
	public void setUsername(String username) {
		this.username = username;
	}
 
}